# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "krack" do
        pod 'AFNetworking', '~> 2.0.3'
        pod 'socket.IO', '~> 0.5.1'
        pod 'FMDB', '~> 2.2'
        pod 'SVProgressHUD', '~> 0.8'
        pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.7'
        pod 'Facebook-iOS-SDK', '~> 3.13.1'
        pod 'GPUImage', '~> 0.1.4'
        pod 'Colours', '~> 2.0'
        pod 'JSONModel', '~> 0.10.0'
        pod 'RSCategories', '~> 0.1'
        pod 'SDWebImage', '~> 3.5'
        pod 'Underscore.m', '~> 0.2.1'
        pod 'BButton',  :git => 'https://github.com/jessesquires/BButton.git'
        pod 'MHTextField', '~> 0.0.2'
        pod 'NZCircularImageView', '~> 0.0.2'
        pod 'NullObjects', '~> 0.0.1'
        pod 'NZBundle', '~> 0.0.4'
        pod 'UIDevice-Helpers', '~> 0.0.2'
        pod 'UzysCircularProgressPullToRefresh', '~> 1.0.5'
        pod 'TWMessageBarManager', '~> 1.3.1'
        pod 'WCFastCell', '~> 1.0'
        pod 'SWTableViewCell', '~> 0.2.4'
        pod 'NZLabel', '~> 0.0.1'
        pod 'TYMActivityIndicatorView', '~> 0.2.0'
        pod 'SIAlertView', '~> 1.3'
        pod 'UINavigationBar+Addition', '~> 1.0.0'
        pod 'AHKActionSheet', '~> 0.1.3'
        pod 'FXImageView', '~> 1.3.3'
	pod 'Google-Maps-iOS-SDK', '~> 1.8.1'
end

target "krackTests" do

end

